import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import HeaderBar from "./Header";

export const metadata: Metadata = {
  title: "Fonte Jurídica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <HeaderBar /> 
        <NavBar />
        {children}
      </body>
    </html>
  );
}
